// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesGridSplitLarge from "@/components/sections/features/FeaturesGridSplitLarge";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
              <FeaturesGridSplitLarge
                textAnimation="fade-blur"
                tag="Beyond the Cup"
                title="Host Your Next Event at Joe's"
                description="From intimate gatherings to full-scale catering, we bring the warmth of Joe's wherever you need it."
                topItems={[
                  {
                    title: "Private Events",
                    description: "Book our space for birthdays, meetings, or just a good excuse to get together. Great coffee and good vibes included.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/joes-coffee/features/private-events.webp",
                  },
                  {
                    title: "Catering",
                    description: "Let us handle the coffee and pastries for your next event. We'll set up, pour, and make sure nobody runs on empty.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/joes-coffee/features/catering.webp",
                  },
                ]}
                bottomItem={{
                  title: "Custom Menus",
                  description: "Work with our team to build a tailored menu for your event — from espresso bars to pastry platters, we've got you covered.",
                  imageSrc: "https://storage.googleapis.com/webild/default/templates/joes-coffee/features/custom-menus.webp",
                  primaryButton: { text: "Get in Touch", href: "#contact" },
                }}
              />
            </div>
  );
}
