// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardBrandFloatingCards from "@/components/sections/hero/HeroBillboardBrandFloatingCards";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroBillboardBrandFloatingCards
                textAnimation="fade-blur"
                brand="Joe's Coffee"
                description="Handcrafted espresso drinks and freshly baked pastries in a warm, welcoming atmosphere. From our first roast to your morning cup, every sip tells a story."
                primaryButton={{ text: "Order Now", href: "#order" }}
                secondaryButton={{ text: "View Menu", href: "#menu" }}
                videoSrc="https://storage.googleapis.com/webild/default/templates/joes-coffee/hero/hero.mp4"
                floatingCards={[
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/joes-coffee/hero/iced-coffee.webp", name: "Americano" },
                  { imageSrc: "https://storage.googleapis.com/webild/default/templates/joes-coffee/hero/latte.webp", name: "Latte" },
                ]}
              />
            </div>
  );
}
